services:
  mysql-db:
    image: mysql:8.1
    container_name: mysql-prueba
    restart: always
    environment:
      MYSQL_DATABASE: prueba
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
